export const TOKENS = Object.freeze({
  APPLICATION: Symbol('APPLICATION'),
  CONFIG: Symbol('CONFIG'),
  LOGGER: Symbol('LOGGER'),
  CONTAINER: Symbol('CONTAINER'),

  PROVIDER_REGISTRY: Symbol('PROVIDER_REGISTRY'),
  PROVIDER_MANAGER: Symbol('PROVIDER_MANAGER'),
  OAUTH_MANAGER: Symbol('OAUTH_MANAGER'),
  OAUTH_SECURITY_SERVICE: Symbol('OAUTH_SECURITY_SERVICE'),
  PROVIDER_CONFIGURATION_SERVICE: Symbol('PROVIDER_CONFIGURATION_SERVICE'),
  RUNTIME_PUBLIC_PROJECTION_SERVICE: Symbol('RUNTIME_PUBLIC_PROJECTION_SERVICE'),
  CUSTOM_PROVIDER_SERVICE: Symbol('CUSTOM_PROVIDER_SERVICE'),
  CREDENTIAL_MANAGER: Symbol('CREDENTIAL_MANAGER'),
  DASHBOARD_SERVICE: Symbol('DASHBOARD_SERVICE'),
  MANAGEMENT_SERVICE: Symbol('MANAGEMENT_SERVICE'),
  ACCESS_MANAGEMENT_SERVICE: Symbol('ACCESS_MANAGEMENT_SERVICE'),
  API_TOKEN_SERVICE: Symbol('API_TOKEN_SERVICE'),
  AUDIT_LOG_SERVICE: Symbol('AUDIT_LOG_SERVICE'),
  EXPORT_SERVICE: Symbol('EXPORT_SERVICE'),
  BACKUP_RESTORE_SERVICE: Symbol('BACKUP_RESTORE_SERVICE'),
  RESTORE_ADMISSION_SERVICE: Symbol('RESTORE_ADMISSION_SERVICE'),
  RESTORE_COMMIT_COORDINATOR: Symbol('RESTORE_COMMIT_COORDINATOR'),
  METRICS_SERVICE: Symbol('METRICS_SERVICE'),
  CREDENTIAL_POLICY_SERVICE: Symbol('CREDENTIAL_POLICY_SERVICE'),
  CREDENTIAL_ROTATION_SERVICE: Symbol('CREDENTIAL_ROTATION_SERVICE'),
  CREDENTIAL_SECRET_VERSION_SERVICE: Symbol('CREDENTIAL_SECRET_VERSION_SERVICE'),
  CREDENTIAL_HISTORY_SERVICE: Symbol('CREDENTIAL_HISTORY_SERVICE'),
  LIFECYCLE_NOTIFICATION_SERVICE: Symbol('LIFECYCLE_NOTIFICATION_SERVICE'),
  PROVIDER_ROTATION_FRAMEWORK: Symbol('PROVIDER_ROTATION_FRAMEWORK'),
  CONSUMER_GRANT_SERVICE: Symbol('CONSUMER_GRANT_SERVICE'),
  CONSUMER_CREDENTIAL_SERVICE: Symbol('CONSUMER_CREDENTIAL_SERVICE'),

  SCHEDULER: Symbol('SCHEDULER'),

  JSON_STORE: Symbol('JSON_STORE'),
  SECURE_JSON_STORE: Symbol('SECURE_JSON_STORE'),
  TOKEN_STORE: Symbol('TOKEN_STORE'),
  CREDENTIAL_STORE: Symbol('CREDENTIAL_STORE'),
  BACKUP_STORE: Symbol('BACKUP_STORE'),
  ACCESS_MANAGEMENT_STORE: Symbol('ACCESS_MANAGEMENT_STORE'),
  API_TOKEN_STORE: Symbol('API_TOKEN_STORE'),
  AUDIT_LOG_STORE: Symbol('AUDIT_LOG_STORE'),
  MANAGEMENT_BACKUP_STORE: Symbol('MANAGEMENT_BACKUP_STORE'),
  CREDENTIAL_POLICY_STORE: Symbol('CREDENTIAL_POLICY_STORE'),
  CREDENTIAL_SECRET_VERSION_STORE: Symbol('CREDENTIAL_SECRET_VERSION_STORE'),
  LIFECYCLE_NOTIFICATION_STORE: Symbol('LIFECYCLE_NOTIFICATION_STORE'),
  PROVIDER_CONFIGURATION_STORE: Symbol('PROVIDER_CONFIGURATION_STORE'),
  CUSTOM_PROVIDER_DEFINITION_STORE: Symbol('CUSTOM_PROVIDER_DEFINITION_STORE'),
  CONSUMER_GRANT_STORE: Symbol('CONSUMER_GRANT_STORE'),

  REFRESH_EXPIRED_TOKENS_COMMAND: Symbol('REFRESH_EXPIRED_TOKENS_COMMAND'),

  TOKEN_LIFECYCLE_SERVICE: Symbol('TOKEN_LIFECYCLE_SERVICE'),
  IMPORT_TOKEN_COMMAND: Symbol('IMPORT_TOKEN_COMMAND'),
  START_OAUTH_COMMAND: Symbol('START_OAUTH_COMMAND'),


  HTTP_CLIENT: Symbol('HTTP_CLIENT'),
  EGRESS_POLICY: Symbol('EGRESS_POLICY'),
  ABUSE_ADMISSION: Symbol('ABUSE_ADMISSION'),

  OAUTH_CALLBACK_SERVER: Symbol('OAUTH_CALLBACK_SERVER'),

  THREADS_API_CLIENT: Symbol('THREADS_API_CLIENT'),
  THREADS_OAUTH_SERVICE: Symbol('THREADS_OAUTH_SERVICE'),
  THREADS_PROVIDER: Symbol('THREADS_PROVIDER'),

  GOOGLE_API_CLIENT: Symbol('GOOGLE_API_CLIENT'),
  GOOGLE_OAUTH_SERVICE: Symbol('GOOGLE_OAUTH_SERVICE'),
  GOOGLE_PROVIDER: Symbol('GOOGLE_PROVIDER'),

  TWITCH_API_CLIENT: Symbol('TWITCH_API_CLIENT'),
  TWITCH_OAUTH_SERVICE: Symbol('TWITCH_OAUTH_SERVICE'),
  TWITCH_PROVIDER: Symbol('TWITCH_PROVIDER'),

  KICK_API_CLIENT: Symbol('KICK_API_CLIENT'),
  KICK_OAUTH_SERVICE: Symbol('KICK_OAUTH_SERVICE'),
  KICK_PROVIDER: Symbol('KICK_PROVIDER'),

  DISCORD_API_CLIENT: Symbol('DISCORD_API_CLIENT'),
  DISCORD_OAUTH_SERVICE: Symbol('DISCORD_OAUTH_SERVICE'),
  DISCORD_PROVIDER: Symbol('DISCORD_PROVIDER'),

  X_API_CLIENT: Symbol('X_API_CLIENT'),
  X_OAUTH_SERVICE: Symbol('X_OAUTH_SERVICE'),
  X_PROVIDER: Symbol('X_PROVIDER'),

  FACEBOOK_API_CLIENT: Symbol('FACEBOOK_API_CLIENT'),
  FACEBOOK_OAUTH_SERVICE: Symbol('FACEBOOK_OAUTH_SERVICE'),
  FACEBOOK_PROVIDER: Symbol('FACEBOOK_PROVIDER'),

  INSTAGRAM_API_CLIENT: Symbol('INSTAGRAM_API_CLIENT'),
  INSTAGRAM_OAUTH_SERVICE: Symbol('INSTAGRAM_OAUTH_SERVICE'),
  INSTAGRAM_PROVIDER: Symbol('INSTAGRAM_PROVIDER'),

  SFTP_CLIENT: Symbol('SFTP_CLIENT'),
  SFTP_CONNECTION_SERVICE: Symbol('SFTP_CONNECTION_SERVICE'),
  SFTP_PROVIDER: Symbol('SFTP_PROVIDER'),

  FTP_CLIENT: Symbol('FTP_CLIENT'),
  FTP_CONNECTION_SERVICE: Symbol('FTP_CONNECTION_SERVICE'),
  FTP_PROVIDER: Symbol('FTP_PROVIDER'),

  OPENAI_CLIENT: Symbol('OPENAI_CLIENT'),
  OPENAI_CONNECTION_SERVICE: Symbol('OPENAI_CONNECTION_SERVICE'),
  OPENAI_PROVIDER: Symbol('OPENAI_PROVIDER')
});
